AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/locales/countries.*.rb'
    - 'lib/tasks/auto_annotate_models.rake'

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Performance/Sample:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
