AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/locales/countries.*.rb'

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Performance/Sample:
  Enabled: false
