language: ruby
cache: bundler
rvm:
  - 2.2.2
addons:
  postgresql: "9.4"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libvirt-bin libvirt-dev qemu qemu-kvm
before_script:
  - wget -P lib/geolite/ http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
  - gunzip -f lib/geolite/GeoLite2-City.mmdb.gz
  - cp config/database.example.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - cp config/settings.example.yml config/settings.yml
  - bin/rake db:setup RAILS_ENV=test
