language: ruby
cache: bundler
rvm:
  - 2.2.2
addons:
  postgresql: "9.4"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libvirt-bin libvirt-dev qemu qemu-kvm
before_script:
  - cp config/database.example.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - cp config/settings.example.yml config/settings.yml
  - bin/rake db:setup RAILS_ENV=test
