default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: virtadmin4_development

test:
  <<: *default
  database: virtadmin4_test

staging:
  <<: *default
  database: virtadmin4_staging
  username: <%= ENV['VIRTADMIN4_DATABASE_USERNAME'] %>
  password: <%= ENV['VIRTADMIN4_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: virtadmin4_production
  username: <%= ENV['VIRTADMIN4_DATABASE_USERNAME'] %>
  password: <%= ENV['VIRTADMIN4_DATABASE_PASSWORD'] %>
