app:
  name: VirtAdmin4
  host: 'localhost:3001'
  keyword: 'vps virtual servers hosting libvirt kvm VirtAdmin4'
  description: VirtAdmin4

  default_locale: 'en'
  default_time_zone: 'UTC' # Run "rake time:zones:all" for a list of time zones.

  maintenance_mode: false

mail:
  sender: 'Company Inc <info@company.inc>'
  subject_prefix: '[Company Inc]'
  admin_address: 'info@company.inc'
  to_all_admins: true

users:
  manual_approval: true # Possible values: true, false 'auto'

company:
  name: Company Inc
  phone: '(747) 302-0938'
  email: 'info@company.inc'
  web: 'https://company.inc/'

geolite2:
  path: 'lib/geolite/GeoLite2-City.mmdb'
